# Generated by Django 2.2.1 on 2019-06-23 16:15

import api.models
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('key', models.CharField(default=api.models.generateRandomKey, max_length=10, unique=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(verbose_name='position')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.ImageField(blank=True, default='static/images/exams/exam.png', max_length=20480, null=True, upload_to='static/images/exams/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice', models.BooleanField(default=False)),
                ('current', models.IntegerField(default=1)),
                ('checkin_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-practice', 'user', 'test'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='static/images/subjects/subject.png', max_length=20480, upload_to='static/images/subjects/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('EXAM', 'Exam'), ('TOPIC', 'Topic'), ('OTHER', 'Others')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('practice', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('activation_time', models.DateField(blank=True, null=True)),
                ('time_alotted', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('sections', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Test Series',
                'verbose_name_plural': 'Test Series',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='static/images/topics/topic.png', max_length=20480, upload_to='static/images/topics/')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('practice', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('activation_time', models.DateField(blank=True, null=True)),
                ('time_alotted', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('sections', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visible', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_tests', to='api.AccessCode')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_tests', to='api.Exam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
