# Generated by Django 2.2.1 on 2019-09-26 21:20

import api.models
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField()),
                ('key', models.CharField(default=api.models.generateRandomKey, max_length=10, unique=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(verbose_name='position')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.CharField(blank=True, default='exam.png', max_length=20480, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('receipt', models.FileField(null=True, upload_to='static/receipts/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('completed', models.BooleanField(default=False)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('current', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('marks', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ranks', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-practice', 'student', 'test'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(blank=True, default='static/images/subjects/subject.png', max_length=20480, upload_to='static/images/subjects/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('EXAM', 'Exam'), ('TOPIC', 'Topic'), ('OTHER', 'Others')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('practice', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('time_alotted', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('sections', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('corrected', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Test Series',
                'verbose_name_plural': 'Test Series',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='static/images/topics/topic.png', max_length=20480, upload_to='static/images/topics/')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'ordering': ['subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_added', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('PAYTM', 'PayTM'), ('OTHERS', 'Others')], max_length=10)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
