# Generated by Django 2.2.1 on 2019-10-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_series', to='api.AccessCode'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Exam'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_series', to='authentication.Institute'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='registered_students',
            field=models.ManyToManyField(blank=True, to='authentication.Student'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Tag'),
        ),
        migrations.AddField(
            model_name='testseries',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Test'),
        ),
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='api.Exam'),
        ),
        migrations.AddField(
            model_name='test',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Institute'),
        ),
        migrations.AddField(
            model_name='test',
            name='registered_students',
            field=models.ManyToManyField(blank=True, to='authentication.Student'),
        ),
        migrations.AddField(
            model_name='test',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.Test'),
        ),
        migrations.AddField(
            model_name='resetcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='test_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TestSeries'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credituse',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute'),
        ),
        migrations.AddField(
            model_name='credituse',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Test'),
        ),
        migrations.AddField(
            model_name='aitstransaction',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute'),
        ),
        migrations.AddField(
            model_name='aitstransaction',
            name='test_series',
            field=models.ManyToManyField(related_name='aits_transactions', to='api.TestSeries'),
        ),
    ]
