# Generated by Django 2.2.1 on 2019-10-21 11:20

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191018_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20000)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('solution', models.CharField(max_length=20000)),
                ('type', models.CharField(choices=[('0', 'Single Correct'), ('1', 'Multiple Correct'), ('2', 'Numerical'), ('3', 'Matrix Match')], max_length=10)),
                ('subjectIndex', models.IntegerField()),
                ('topicIndex', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('0', 'Very Easy'), ('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Very Hard')], max_length=10)),
            ],
        )
    ]
