# Generated by Django 2.2.1 on 2019-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0002_auto_20190625_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='registered_student',
            field=models.ManyToManyField(blank=True, to='authentication.Student'),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='registered_student',
            field=models.ManyToManyField(blank=True, to='authentication.Student'),
        ),
    ]
