# Generated by Django 2.2.1 on 2019-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190927_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='aits',
            field=models.BooleanField(default=False),
        ),
    ]
