# Generated by Django 2.2.1 on 2019-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190924_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
