# Generated by Django 2.2.1 on 2019-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190817_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='test_series',
        ),
        migrations.AddField(
            model_name='testseries',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Test'),
        ),
        migrations.DeleteModel(
            name='UnitTest',
        ),
    ]
