# Generated by Django 2.2.1 on 2019-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payment_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testseries',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
