# Generated by Django 2.2.1 on 2019-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190925_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
