# Generated by Django 2.2.1 on 2019-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190818_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
