# Generated by Django 2.2.1 on 2019-09-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='acess_code',
            field=models.CharField(max_length=6),
        ),
    ]
