# Generated by Django 2.2.1 on 2019-08-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_session_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current',
        ),
    ]
