# Generated by Django 2.2.1 on 2019-11-04 18:15

from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_test_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='testseries',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='testseries',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Offer'),
        ),
    ]
