# Generated by Django 2.2.1 on 2019-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191001_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
