# Generated by Django 2.2.1 on 2019-11-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191104_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='syllabus',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
