# Generated by Django 2.2.1 on 2019-08-19 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_session_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
