# Generated by Django 2.2.1 on 2019-08-20 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='marks',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
