# Generated by Django 2.2.1 on 2019-10-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0007_auto_20191001_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITSTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('PAYTM', 'PayTM'), ('OTHERS', 'Others')], max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt', models.FileField(null=True, upload_to='static/institute/receipts/')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute')),
                ('test_series', models.ManyToManyField(related_name='test_series', to='api.TestSeries')),
            ],
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
