# Generated by Django 2.2.1 on 2019-08-23 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_test_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='marks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
