# Generated by Django 2.2.1 on 2019-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191001_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AlterField(
            model_name='aitstransaction',
            name='test_series',
            field=models.ManyToManyField(related_name='aits_transactions', to='api.TestSeries'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
