# Generated by Django 2.2.1 on 2019-10-02 19:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191002_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ranklist',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
