# Generated by Django 2.2.1 on 2019-08-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_institute_current_credits'),
        ('api', '0010_auto_20190823_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_added', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('PAYTM', 'PayTM'), ('OTHERS', 'Others')], max_length=10)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='CreditUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Institute')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Test')),
            ],
        ),
    ]
