# Generated by Django 2.2.1 on 2019-10-04 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20191003_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitstransaction',
            name='receipt',
            field=models.FileField(null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ImageField(storage=etests.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qimages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
