# Generated by Django 2.2.1 on 2019-10-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191004_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitstransaction',
            name='receipt',
            field=models.FileField(null=True, upload_to='static/institute/receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(null=True, upload_to='static/receipts/'),
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
