# Generated by Django 2.2.1 on 2019-09-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
