# Generated by Django 2.2.1 on 2019-10-05 05:30

from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191005_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitstransaction',
            name='receipt',
            field=models.FileField(null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
