# Generated by Django 2.2.1 on 2019-09-06 18:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_test_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
