# Generated by Django 2.2.1 on 2019-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_test_corrections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='stats',
            new_name='ranks',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='corrections',
            new_name='corrected',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='closed',
            new_name='finished',
        ),
        migrations.RemoveField(
            model_name='test',
            name='active',
        ),
        migrations.AddField(
            model_name='test',
            name='closing_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
