# Generated by Django 2.2.1 on 2019-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190908_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
