# Generated by Django 2.2.1 on 2019-09-08 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190908_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='checkin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
