# Generated by Django 2.2.1 on 2019-09-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190908_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='registered_student',
            new_name='registered_students',
        ),
    ]
