# Generated by Django 2.2.1 on 2019-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190909_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.CharField(blank=True, default='exam.png', max_length=20480, null=True),
        ),
    ]
