# Generated by Django 2.2.1 on 2019-09-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190909_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testseries',
            old_name='registered_student',
            new_name='registered_students',
        ),
    ]
