# Generated by Django 2.2.1 on 2019-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190911_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testseries',
            name='exam',
        ),
        migrations.AddField(
            model_name='testseries',
            name='exam',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Exam'),
        ),
    ]
