# Generated by Django 2.2.1 on 2019-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190919_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
