# Generated by Django 2.2.1 on 2019-09-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190920_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testseries',
            name='exams',
        ),
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='api.Exam'),
        ),
    ]
