# Generated by Django 2.2.1 on 2019-09-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testseries',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='test_series', to='api.Exam'),
        ),
    ]
