# Generated by Django 2.2.1 on 2019-08-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='institute',
        ),
        migrations.AddField(
            model_name='student',
            name='institutes',
            field=models.ManyToManyField(blank=True, to='authentication.Institute'),
        ),
    ]
