# Generated by Django 2.2.1 on 2019-10-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
