# Generated by Django 2.2.1 on 2019-10-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_institute_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='following',
        ),
    ]
