# Generated by Django 2.2.1 on 2019-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_enrollment_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='verified',
        ),
        migrations.AddField(
            model_name='institute',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
