# Generated by Django 2.2.1 on 2019-08-26 14:58

import authentication.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190824_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_key', models.CharField(default=authentication.utils.randomKey, max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institute')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='institutes',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Batch')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Student')),
            ],
        ),
    ]
