# Generated by Django 2.2.1 on 2019-11-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_student_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
