# Generated by Django 2.2.1 on 2019-11-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_institute_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='about',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
