# Generated by Django 2.2.1 on 2019-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190826_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institutes',
            field=models.ManyToManyField(blank=True, through='authentication.Enrollment', to='authentication.Institute'),
        ),
    ]
