# Generated by Django 2.2.1 on 2019-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_student_institutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='current_credits',
            field=models.IntegerField(default=0),
        ),
    ]
