# Generated by Django 2.2.1 on 2019-08-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_institute_current_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='authentication.Institute'),
        ),
    ]
