# Generated by Django 2.2.1 on 2019-08-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190826_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='authentication.Batch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='authentication.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institutes',
            field=models.ManyToManyField(blank=True, related_name='students', through='authentication.Enrollment', to='authentication.Institute'),
        ),
    ]
