# Generated by Django 2.2.1 on 2019-08-27 20:49

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20190827_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='joining_key',
            field=models.CharField(default=authentication.utils.randomKey, max_length=8),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='roll_number',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
