# Generated by Django 2.2.1 on 2019-08-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190827_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authentication.Batch'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='roll_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='authentication.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('batch', 'roll_number')},
        ),
    ]
