# Generated by Django 2.2.1 on 2019-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190830_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_students', to='authentication.Institute'),
        ),
    ]
