# Generated by Django 3.2 on 2024-12-30 12:04

import api.models
import api.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import etests.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(default=api.utils.random_key, max_length=100)),
                ('email', api.models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('image', models.CharField(blank=True, max_length=2048, null=True)),
                ('site', models.CharField(blank=True, max_length=250, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_student', models.BooleanField(default=False)),
                ('is_institute', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_key', models.CharField(default=api.utils.random_key, max_length=8)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=25)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(verbose_name='position')),
                ('name', models.CharField(max_length=200)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.CharField(blank=True, default='exam.png', max_length=20480, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(storage=etests.storage_backends.MediaStorage(), upload_to='', validators=[api.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('current_credits', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('about', models.CharField(blank=True, max_length=1024, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('carousel', models.JSONField(blank=True, default=list, null=True)),
                ('notifications', models.JSONField(blank=True, default=list, null=True)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('team', models.JSONField(blank=True, default=list, null=True)),
                ('toppers', models.JSONField(blank=True, default=list, null=True)),
                ('downloads', models.JSONField(blank=True, default=list, null=True)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('gallery', models.JSONField(blank=True, default=list, null=True)),
                ('faqs', models.JSONField(blank=True, default=list, null=True)),
                ('courses', models.JSONField(blank=True, default=list, null=True)),
                ('centers', models.JSONField(blank=True, default=list, null=True)),
                ('contacts', models.JSONField(blank=True, default=dict, null=True)),
                ('faculty', models.JSONField(blank=True, default=list, null=True)),
                ('links', models.JSONField(blank=True, default=list, null=True)),
                ('forms', models.JSONField(blank=True, default=list, null=True)),
                ('extras', models.JSONField(blank=True, default=api.models.Institute.extras_default, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(storage=etests.storage_backends.MediaStorage(), upload_to='', validators=[api.models.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('institutes', models.ManyToManyField(blank=True, related_name='students', through='api.Enrollment', to='api.Institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('aits', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('time_alotted', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('sections', models.JSONField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('corrected', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=False)),
                ('marks_list', models.JSONField(blank=True, null=True)),
                ('syllabus', models.CharField(blank=True, max_length=1024, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='api.exam')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.institute')),
                ('registered_batches', models.ManyToManyField(blank=True, related_name='tests', to='api.Batch')),
                ('registered_students', models.ManyToManyField(blank=True, related_name='tests', to='api.Student')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='TestSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
                ('exams', models.ManyToManyField(blank=True, related_name='test_series', to='api.Exam')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_series', to='api.institute')),
                ('registered_students', models.ManyToManyField(blank=True, to='api.Student')),
                ('tests', models.ManyToManyField(blank=True, related_name='test_series', to='api.Test')),
            ],
            options={
                'verbose_name': 'Test Series',
                'verbose_name_plural': 'Test Series',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_added', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('PAYTM', 'PayTM'), ('OTHERS', 'Others')], max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.subject')),
            ],
            options={
                'ordering': ('subject', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TestSeriesTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('NETBANKING', 'Netbanking'), ('PAYTM', 'PayTM'), ('OTHERS', 'Others')], max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt', models.FileField(blank=True, null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institute')),
                ('test_series', models.ManyToManyField(related_name='aits_transactions', to='api.TestSeries')),
            ],
            options={
                'verbose_name_plural': 'Test Series Transactions',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=10800))),
                ('completed', models.BooleanField(default=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=list, null=True)),
                ('current', models.JSONField(blank=True, null=True)),
                ('marks', models.JSONField(blank=True, null=True)),
                ('ranks', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.student')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.test')),
            ],
            options={
                'ordering': ('practice', 'checkin_time', 'test', 'student'),
            },
        ),
        migrations.CreateModel(
            name='ResetCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reset_code', models.CharField(max_length=6)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=20000)),
                ('answer', models.JSONField()),
                ('solution', models.CharField(blank=True, max_length=20000, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Single Correct'), (1, 'Multiple Correct'), (2, 'Numerical'), (3, 'Matrix Match'), (4, 'Paragraph')])),
                ('difficulty', models.IntegerField(blank=True, choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard')], null=True)),
                ('correct_marks', models.FloatField(default=4)),
                ('partial_marks', models.FloatField(default=0)),
                ('incorrect_marks', models.FloatField(default=1)),
                ('option_count', models.IntegerField(default=4)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exam')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institute')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.question')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.test')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.topic')),
            ],
            options={
                'ordering': ('subject', 'topic', 'type', 'difficulty'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('receipt', models.FileField(blank=True, null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.student')),
                ('test_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testseries')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institute'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='api.student'),
        ),
        migrations.CreateModel(
            name='CreditUse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.institute')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.test')),
            ],
            options={
                'verbose_name_plural': 'Credits Usage',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institute')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.institute'),
        ),
    ]
