# Generated by Django 3.0.3 on 2020-03-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, 'Very Easy'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Very Hard')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Single Correct'), (1, 'Multiple Correct'), (2, 'Numerical'), (3, 'Matrix Match')]),
        ),
        migrations.AlterField(
            model_name='test',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.Institute'),
        ),
    ]
