# Generated by Django 3.0.2 on 2020-01-26 16:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['practice', 'checkin_time', 'test', 'student']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='practice',
        ),
        migrations.AlterField(
            model_name='session',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
