# Generated by Django 3.0.2 on 2020-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200126_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='registered_batches',
            field=models.ManyToManyField(blank=True, to='api.Batch'),
        ),
    ]
