# Generated by Django 2.2.1 on 2019-12-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191112_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitstransaction',
            options={'verbose_name_plural': 'AITS Transactions'},
        ),
        migrations.AlterModelOptions(
            name='credituse',
            options={'verbose_name_plural': 'Credits Usage'},
        ),
    ]
