# Generated by Django 3.0.2 on 2020-01-29 19:10

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_registered_batches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='testseries',
            name='tags',
        ),
        migrations.AddField(
            model_name='exam',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='registered_batches',
            field=models.ManyToManyField(blank=True, related_name='tests', to='api.Batch'),
        ),
        migrations.AlterField(
            model_name='test',
            name='registered_students',
            field=models.ManyToManyField(blank=True, related_name='tests', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AccessCode',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
