# Generated by Django 3.0.3 on 2020-03-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200304_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('subject', 'position', 'name')},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='exams',
            new_name='exam',
        ),
    ]
