# Generated by Django 3.0.2 on 2020-01-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200130_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AITSTransaction',
            new_name='TestSeriesTransaction',
        ),
    ]
