# Generated by Django 3.0.3 on 2020-03-05 07:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200305_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_marks',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_marks',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Institute'),
        ),
        migrations.AddField(
            model_name='question',
            name='partial_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.Subject'),
        ),
    ]
