# Generated by Django 3.0.3 on 2020-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200305_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_count',
            field=models.IntegerField(default=4),
        ),
    ]
