# Generated by Django 3.0.2 on 2020-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200131_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subjectIndex',
            new_name='subject_index',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='topicIndex',
            new_name='topic_index',
        ),
    ]
