# Generated by Django 3.0.2 on 2020-01-31 14:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200131_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
