# Generated by Django 3.0.3 on 2020-03-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_question_option_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('subject', 'topic', 'type', 'difficulty')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic_index',
        ),
    ]
