# Generated by Django 3.0.2 on 2020-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200205_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('0', 'Very Easy'), ('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard'), ('4', 'Very Hard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
