# Generated by Django 3.0.3 on 2020-03-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_institute_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('practice', 'checkin_time', 'test', 'student')},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterModelOptions(
            name='testseries',
            options={'ordering': ('-date_added',), 'verbose_name': 'Test Series', 'verbose_name_plural': 'Test Series'},
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.Question'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='handle',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='institutes', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Single Correct'), (1, 'Multiple Correct'), (2, 'Numerical'), (3, 'Matrix Match'), (4, 'Paragraph')]),
        ),
    ]
