# Generated by Django 3.0.3 on 2020-04-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200403_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='faq',
            new_name='faqs',
        ),
    ]
