# Generated by Django 3.0.3 on 2020-04-04 19:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200404_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='notifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='institute',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
