# Generated by Django 3.0.3 on 2020-04-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200406_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Institute',
            new_name='institute',
        ),
    ]
