# Generated by Django 3.0.3 on 2020-04-12 08:41

import api.models
from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200412_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(storage=etests.storage_backends.InstituteMediaStorage(), upload_to='', validators=[api.models.validate_file_size])),
            ],
        ),
    ]
