# Generated by Django 3.0.3 on 2020-04-16 07:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200415_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
