# Generated by Django 3.0.3 on 2020-04-22 14:05

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_institute_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='joining_key',
            field=models.CharField(default=api.utils.random_key, max_length=20),
        ),
    ]
