# Generated by Django 3.0.3 on 2020-04-24 12:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_institute_joining_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
