# Generated by Django 3.0.3 on 2020-06-27 05:00

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200626_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='joining_key',
            field=models.CharField(default=api.utils.random_key, max_length=8),
        ),
        migrations.AddField(
            model_name='test',
            name='registered_batches',
            field=models.ManyToManyField(blank=True, related_name='tests', to='api.Batch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.Institute'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=25)),
                ('joining_key', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('date_joined', models.DateField(null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.Batch')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='api.Student')),
            ],
            options={
                'unique_together': {('batch', 'roll_number')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='new_institutes',
            field=models.ManyToManyField(blank=True, related_name='new_students', through='api.Enrollment', to='api.Institute'),
        ),
    ]
