# Generated by Django 3.0.3 on 2020-06-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_enrollment_joining_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='joining_key',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='students',
        ),
    ]
