# Generated by Django 3.0.3 on 2020-06-27 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200627_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('id',), 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
