# Generated by Django 3.0.3 on 2020-07-21 06:31

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200627_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=api.models.Institute.extras_default, null=True),
        ),
    ]
