# Generated by Django 3.2 on 2022-01-16 07:09

import api.models
from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220111_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='carousel',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='centers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='contacts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='courses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='downloads',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='extras',
            field=models.JSONField(blank=True, default=api.models.Institute.extras_default, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='faculty',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='faqs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='forms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='notifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='team',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='toppers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=etests.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='current',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='marks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ranks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='result',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='marks_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='sections',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testseriestransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=etests.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
