# Generated by Django 3.2 on 2022-01-16 07:25

from django.db import migrations, models
import etests.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220116_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='testseriestransaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=etests.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
