export const subjectTopics = {
  subjects: ["Physics", "Mathematics", "Chemistry", "botany", "Zoology"],
  topics: [
    [
      "Physics and Measurement",
      "Kinematics",
      "Laws of Motion",
      "Work",
      "Energy and Power",
      "Rotational Motion",
      "Gravitation",
      "Properties of Solids and Liquids",
      "Thermodynamics",
      "Kinetic Theory of Gases",
      "Oscillations and Waves",
      "Electrostatics",
      "Current Electricity",
      "Magnetic Effects of Current and Magnetism",
      "Electromagnetic Induction and Alternating Currents",
      "Electromagnetic Waves",
      "Optics",
      "Dual Nature of Matter and Radiation",
      "Atoms and Nuclei",
      "Electronic Devices",
      "Communication Systems",
      "Experimental Skills",
      "Thermal Physics"
    ],
    [
      "Sets, relations and functions",
      "Complex numbers and quadratic equations",
      "Matrices and determinants",
      "Permutations and combinations",
      "Mathematical induction",
      "Binomial theorem and its simple applications",
      "Sequences and series",
      "Limit, continuity and differentiability",
      "Integral calculus",
      "Differential equations",
      "Three dimensional geometry",
      "Vector algebra",
      "Statistics and probability",
      "Trigonometry",
      "Mathematical reasoning"
    ],
    [
      "Some Basic Concepts in Chemistry",
      "States of Matter",
      "Atomic Structure",
      "Chemical Bonding and Molecular Structure",
      "Chemical Thermodynamics",
      "Solutions",
      "Equilibrium",
      "Redox Reactions and Electro-chemistry",
      "Chemical Kinetics",
      "Surface Chemistry",
      "Classification of Elements and Periodicity in Properties",
      "General Principles and Processes of Isolation of Metals.",
      "Hydrogen",
      "S-Block Elements (Alkali and Alkaline Earth Metals)",
      "P-Block Elements",
      "d and f Block Elements",
      "Co-Ordination Compounds",
      "Environmental Chemistry",
      "Purification and Characterization of Organic Compounds",
      "Some Basic Principles of Organic Chemistry",
      "Hydrocarbons",
      "Organic Compounds Containing Halogens",
      "Organic Compounds Containing Oxygen",
      "Organic Compounds Containing Nitrogen",
      "Polymers",
      "Biomolecules",
      "Chemistry In Everyday Life",
      "Principles Related to Practical Chemistry"
    ],
    [
      "Biological Classification",
      "Kingdom Monera",
      "Virus",
      "Cell Biology",
      "Cell Division",
      "Mitochondria",
      "Prokaryotic Cell",
      "Ecology",
      "Biodiversity",
      "Biosphere Reverse",
      "Ecosystem",
      "Environmental Issues",
      "Population Growth Model",
      "Stratification",
      "Genetics",
      "Blood Grouping",
      "Genetic Disorders",
      "Mendal’s Biography",
      "Mendal’s Selected Characters",
      "Living World",
      "Taxonomics Aids",
      "Molecular Basis of Inheritance",
      "DNA PAcking",
      "DNA Replication",
      "Genetic Code",
      "Genetic Material",
      "RNA Processing",
      "Morphology",
      "Root Modifiation",
      "Morphology of flowering plants",
      "Fruit",
      "Plant Anatomy",
      "Secondary Growth",
      "Wood",
      "Plant Kingdom",
      "Algae",
      "Angiosperms",
      "Gymnosperms",
      "Life Cycles",
      "Mycorrhizae",
      "Plant Morphology",
      "Root",
      "Steam Modification",
      "Cellular Respiration",
      "Mineral Nutrition-Biological Nitrogen Fixation",
      "Photosynthesis",
      "Plant Growth and Development",
      "Water Transport",
      "Water Transport- Water Potential",
      "Reproduction in Flowering Plant",
      "Embryo Sac",
      "Endosperm",
      "Pollination"
    ],
    [
      "Animal Kingdom",
      "Chordates and Hemichordates",
      "Mammals",
      "Porifera",
      "Animal Morphology",
      "Frog",
      "Animal Physiology",
      "Frog Reproductive System",
      "Biomolecules",
      "DNA",
      "Enzymes",
      "Lipids",
      "RNA processing",
      "Biotechnology",
      "Artificial Vector",
      "PAGE",
      "Evolution",
      "Horse Evolution",
      "Human Health and Disease",
      "Immune System",
      "Infectious Disease",
      "Human Physiology",
      "Circulatory System",
      "Digestive System",
      "Endochrine System",
      "Excretory System",
      "Nervous System",
      "Respiratory System",
      "Sense Organs",
      "Skeleton System",
      "Human Reproduction",
      "Male Reproductive System",
      "Microbes in Human Welfare",
      "Bioprocessing",
      "Industrial Products",
      "Sewage Treatment",
      "Reproductive Health",
      "Artificial Fertilisation",
      "Contraceptives Method",
      "Strategies for Enhancement of Food Production",
      "Animal Husbandry",
      "Artificial Selection"
    ]
  ]
};
