# Generated by Django 2.2.1 on 2019-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='joining_key',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
